{"name": "Login failed test", "status": "passed", "steps": [{"name": "Entering incorrect data so that the login fails", "status": "passed", "parameters": [{"name": "username", "value": "'testuser@test.pl'"}, {"name": "password", "value": "'vAb!@#42563gbh&&*'"}], "start": 1669048156067, "stop": 1669048156805}], "attachments": [{"name": "stdout", "source": "f5680e76-e551-4bb9-8ade-02821ca72742-attachment.txt", "type": "text/plain"}], "start": 1669048155123, "stop": 1669048156806, "uuid": "78e630a5-7286-4cf3-adb8-494bf675e798", "historyId": "97471b02e53f4f2008f686edd919def3", "testCaseId": "11aad89389aef7773ef3ffa94c38d4e7", "fullName": "tests.first_file_test.TestLogIn#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "first_file_test"}, {"name": "subSuite", "value": "TestLogIn"}, {"name": "host", "value": "LAPTOP-EC8GS2UB"}, {"name": "thread", "value": "19252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.first_file_test"}]}